### ISSUE TITLE
建议支持自定义配置附件(图片等)目录

### ISSUE THREAD

**Issue by JingchengLi** [cyanzhong/docs.taio.app#4]
最近发现了Taio这个软件，没想到还是中国人写的，大赞一个！

说下我的需求：
我平时也用obsidian、logseq等双链笔记app，并且多个app使用相同的文件目录，
但是遇到一个比较令人头痛的问题就是Markdown笔记里的本地图片的识别问题，
不同的app对于本地图片目录的默认路径设置和图片路径识别都不一样，会导致在这个app里写的笔记，到了另一个app里，图片无法显示。obsidian支持了类似附件目录修改的配置(如下)，但是在Taio上还没看到，希望能支持。谢谢~

![image](https://user-images.githubusercontent.com/5918144/198523886-882d00f2-9180-43a0-b5c2-4e02098e4191.png)

**Comment by cyanzhong** [comment]
感谢反馈。我们有计划支持动态的存放目录，此 ticket 先关闭。

建议使用内建的反馈渠道方便更容易地被看到，这个 repo 是存放文档用的。
